[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.0" # Ruff version.
hooks = [
  # Run the linter.
  { id = "ruff-check", args = ["--fix"], types_or = ["python", "pyi"] },

  # Run the formatter.
  { id = "ruff-format", types_or = ["python", "pyi"] },
]

[[repos]]
repo = "local"
hooks = [
  # Type check with ty (also enforced in CI).
  { id = "ty-check",
    name = "ty check",
    entry = "uv run ty check",
    language = "system",
    pass_filenames = false,
    types_or = ["python", "pyi",] },
    { id = "pytest",
    name = "pytest",
    entry = "uv run pytest -x -q -m 'not slow'",
    language = "system",
    pass_filenames = false,
    always_run = true,
    }
]
